services:
  - type: web
    name: transportadora
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --log-level debug
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.9.18
